name: SIG Event Update
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install python depencencies
        run: pip install pyyaml
      - name: Update SIG Event File
        run: python .utils/events.py ${{ github.event.before }} ${{ github.event.after }}
      - name: Commit the Change
        uses: stefanzweifel/git-auto-commit-action@v4
